
---
apiVersion: v1
kind: Namespace
metadata:
  name: prometheus
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: martindenh
  annotations:
    argocd.argoproj.io/sync-wave: "-1"

