apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: azure-vote-redis
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/M-Sahin/gitops-kubernetes-demo.git
    targetRevision: HEAD
    path: apps/redis
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: {{ .Values.spec.environment }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true